#Definition of the sort_dictionary() function which takes one dictionary as an input...
def sort_dictionary(_dict):
    
    #Sort the dictionary based on the age value...
    sorted_keys = sorted(_dict.keys(), key = lambda x: _dict[x][1])
    
    #Create one empty list called result...
    result = []
    
    #Use the for loop to go all sorted_keys...
    for k in sorted_keys:
        
        #Create tuple with name and phone number...
        _tuple = (k,_dict[k][0])
        
        #Append the _tuple to result list...
        result.append(_tuple)
        
    #Return the result...
    return result
    

#Create one dictionary...
_dict = {'Tom': (5464512, 24), 'Sara': (5446987, 32), 'Mary': (1557896, 20)}

#Call the sort_dictionary() function and store the result...
result = sort_dictionary(_dict)

#Print the result...
print(result)
